version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: yaem
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root12345

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: root12345
      MINIO_ADDRESS: :9000
      MINIO_CONSOLE_ADDRESS: :9001
      command: minio server /data

  minio-client:
    image: minio/mc:latest
    container_name: minio-client
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host rm expo;
      /usr/bin/mc config host add --quiet --api s3v4 local http://minio:9000 root root12345;
      /usr/bin/mc rb --force local/media/;
      /usr/bin/mc mb --quiet local/media/;
      /usr/bin/mc policy set public local/media;
      "
    depends_on:
      - minio
