# Generated by Django 4.2.2 on 2023-06-12 11:24

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('logo', models.ImageField(blank=True, upload_to='logo', verbose_name='Лого')),
                ('description', models.TextField(verbose_name='Описание')),
                ('working_time', models.CharField(max_length=20, verbose_name='Рабочеее время')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес')),
                ('phone', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Телефон')),
                ('inst', models.CharField(blank=True, max_length=100, verbose_name='Instagram')),
                ('status', models.BooleanField(verbose_name='Активен')),
                ('outside', models.BooleanField(verbose_name='Самовывоз')),
                ('delivery', models.BooleanField(verbose_name='Доставка')),
                ('url_name', models.CharField(blank=True, max_length=30, unique=True, verbose_name='/url')),
                ('visitors', models.IntegerField(blank=True, default=0, verbose_name='Посетителей')),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Заведение',
                'verbose_name_plural': 'Заведения',
            },
        ),
        migrations.CreateModel(
            name='Client_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Область')),
            ],
            options={
                'verbose_name': 'Область',
                'verbose_name_plural': 'Области',
            },
        ),
        migrations.CreateModel(
            name='Food_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Категория')),
                ('client', models.ManyToManyField(blank=True, to='main.client')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Food_type2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Подкатегория')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.food_type', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Блюдо_RU')),
                ('name_kz', models.CharField(blank=True, max_length=50, verbose_name='Блюдо_KZ')),
                ('name_en', models.CharField(blank=True, max_length=50, verbose_name='Блюдо_EN')),
                ('image', models.ImageField(blank=True, upload_to='dishes', verbose_name='Фото')),
                ('description', models.TextField(blank=True, max_length=100, verbose_name='Описание')),
                ('stop', models.BooleanField(verbose_name='Стоп Лист')),
                ('old_price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Старая цена')),
                ('actual_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Текущая цена')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client', verbose_name='Заведение')),
                ('food_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.food_type', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
        migrations.CreateModel(
            name='Client_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client_type', verbose_name='Область')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client', verbose_name='Заведение')),
            ],
            options={
                'verbose_name': 'Заведение-Область',
                'verbose_name_plural': 'Заведение - Области',
            },
        ),
    ]
