# Generated by Django 4.2.2 on 2023-08-25 08:19

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="logo",
            field=models.ImageField(
                upload_to=main.models.client_logo_upload_to, verbose_name="Лого"
            ),
        ),
    ]
