# Generated by Django 4.2.2 on 2023-08-21 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Категория")),
            ],
            options={
                "verbose_name": "Кодкатегория",
                "verbose_name_plural": "Кодкатегории",
            },
        ),
        migrations.AddField(
            model_name="food_type2",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.category",
                verbose_name="Категория",
            ),
        ),
    ]
