# Generated by Django 4.2.2 on 2023-06-13 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_dish_food_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main.city",
                verbose_name="Город",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="description",
            field=models.TextField(max_length=60, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(max_length=20, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="client",
            name="url_name",
            field=models.CharField(max_length=30, unique=True, verbose_name="/url"),
        ),
        migrations.AlterField(
            model_name="dish",
            name="description",
            field=models.TextField(blank=True, max_length=60, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="dish",
            name="name",
            field=models.CharField(max_length=20, verbose_name="Блюдо_RU"),
        ),
    ]
