# Generated by Django 4.2.2 on 2023-08-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_category_food_type2_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(max_length=30, null=True, verbose_name="Категория"),
        ),
        migrations.AddField(
            model_name="category",
            name="name_kk",
            field=models.CharField(max_length=30, null=True, verbose_name="Категория"),
        ),
        migrations.AddField(
            model_name="category",
            name="name_ru",
            field=models.CharField(max_length=30, null=True, verbose_name="Категория"),
        ),
    ]
