# Generated by Django 4.2.2 on 2023-08-25 08:31

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_client_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=main.models.dish_image_upload_to,
                verbose_name="Фото",
            ),
        ),
    ]
