# Generated by Django 4.2.2 on 2023-10-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_dish_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="food_type2",
            options={
                "verbose_name": "Подкатегория",
                "verbose_name_plural": "Подкатегории",
            },
        ),
        migrations.RemoveField(
            model_name="food_type2",
            name="client",
        ),
        migrations.AddField(
            model_name="food_type2",
            name="client",
            field=models.ManyToManyField(
                blank=True, null=True, to="main.client", verbose_name="Клиент"
            ),
        ),
    ]
