# Generated by Django 4.2.2 on 2023-08-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_category_z_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="z_index",
            field=models.IntegerField(
                blank=True, null=True, unique=True, verbose_name="Порядковый №"
            ),
        ),
    ]
