# Generated by Django 4.2.2 on 2023-10-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_food_type2_client"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstablishmentRates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("bronze", "бронза"),
                            ("silver", "серебро"),
                            ("gold", "золото"),
                        ],
                        default="bronze",
                        max_length=15,
                    ),
                ),
            ],
        ),
    ]
