# Generated by Django 4.2.2 on 2023-06-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_food_type2_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Блюдо_RU'),
        ),
    ]
