# Generated by Django 4.2.2 on 2023-08-21 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_category_z_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="food_type2",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.client",
                verbose_name="Клиент",
            ),
        ),
    ]
