# Generated by Django 4.2.2 on 2023-10-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_establishmentrates"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="establishmentrates",
            options={"verbose_name": "Тариф", "verbose_name_plural": "Тарифы"},
        ),
        migrations.AlterField(
            model_name="establishmentrates",
            name="name",
            field=models.CharField(
                choices=[
                    ("bronze", "БРОНЗА"),
                    ("silver", "СЕРЕБРО"),
                    ("gold", "ЗОЛОТО"),
                ],
                default="bronze",
                max_length=15,
                verbose_name="Название тарифа",
            ),
        ),
    ]
