# Generated by Django 4.2.2 on 2023-08-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_food_type2_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="tarif_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
