# Generated by Django 4.2.2 on 2023-10-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_alter_establishmentrates_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="establishmentrates",
            name="name",
            field=models.CharField(
                choices=[
                    ("bronze", "БРОНЗА"),
                    ("silver", "СЕРЕБРО"),
                    ("gold", "ЗОЛОТО"),
                ],
                max_length=15,
                unique=True,
                verbose_name="Название тарифа",
            ),
        ),
    ]
