# Generated by Django 4.2.2 on 2023-08-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_client_tarif_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="tarif_number",
            field=models.IntegerField(blank=True, null=True, verbose_name="Тариф(1-3)"),
        ),
    ]
