# Generated by Django 4.2.2 on 2023-10-09 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_alter_establishmentrates_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="tarif_number",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.establishmentrates",
                verbose_name="Тариф",
            ),
        ),
    ]
