# Generated by Django 4.2.2 on 2023-08-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_alter_dish_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="description_en",
            field=models.TextField(max_length=60, null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="client",
            name="description_kz",
            field=models.TextField(max_length=60, null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="client",
            name="description_ru",
            field=models.TextField(max_length=60, null=True, verbose_name="Описание"),
        ),
    ]
