# Generated by Django 4.2.2 on 2023-08-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_alter_client_tarif_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="z_index",
            field=models.IntegerField(
                blank=True, null=True, unique=True, verbose_name="Порядковый №"
            ),
        ),
        migrations.AddField(
            model_name="dish",
            name="z_index",
            field=models.IntegerField(
                blank=True, null=True, unique=True, verbose_name="Порядковый №"
            ),
        ),
        migrations.AddField(
            model_name="food_type2",
            name="z_index",
            field=models.IntegerField(
                blank=True, null=True, unique=True, verbose_name="Порядковый №"
            ),
        ),
    ]
