# Generated by Django 4.2.2 on 2023-10-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_alter_client_tarif_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="establishmentrates",
            name="name",
            field=models.CharField(
                choices=[
                    ("БРОНЗА", "БРОНЗА"),
                    ("СЕРЕБРО", "СЕРЕБРО"),
                    ("ЗОЛОТО", "ЗОЛОТО"),
                ],
                max_length=15,
                unique=True,
                verbose_name="Название тарифа",
            ),
        ),
    ]
