# Generated by Django 4.2.2 on 2023-08-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_client_description_en_client_description_kz_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="address_en",
            field=models.CharField(max_length=50, null=True, verbose_name="Адрес"),
        ),
        migrations.AddField(
            model_name="client",
            name="address_kz",
            field=models.CharField(max_length=50, null=True, verbose_name="Адрес"),
        ),
        migrations.AddField(
            model_name="client",
            name="address_ru",
            field=models.CharField(max_length=50, null=True, verbose_name="Адрес"),
        ),
        migrations.AddField(
            model_name="food_type2",
            name="name_en",
            field=models.CharField(
                max_length=30, null=True, verbose_name="Подкатегория"
            ),
        ),
        migrations.AddField(
            model_name="food_type2",
            name="name_kz",
            field=models.CharField(
                max_length=30, null=True, verbose_name="Подкатегория"
            ),
        ),
        migrations.AddField(
            model_name="food_type2",
            name="name_ru",
            field=models.CharField(
                max_length=30, null=True, verbose_name="Подкатегория"
            ),
        ),
    ]
