# Generated by Django 4.2.2 on 2023-08-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_client_z_index_dish_z_index_food_type2_z_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="two_gis",
            field=models.CharField(
                blank=True, max_length=150, null=True, unique=True, verbose_name="2gis"
            ),
        ),
    ]
