# Generated by Django 4.2.2 on 2023-08-04 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_client_address_en_client_address_kz_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="food_type2",
            name="category_en",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.food_type",
                verbose_name="Категория",
            ),
        ),
        migrations.AddField(
            model_name="food_type2",
            name="category_kz",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.food_type",
                verbose_name="Категория",
            ),
        ),
        migrations.AddField(
            model_name="food_type2",
            name="category_ru",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.food_type",
                verbose_name="Категория",
            ),
        ),
    ]
