# Generated by Django 4.2.2 on 2023-10-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_alter_establishmentrates_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="working_time",
            field=models.CharField(max_length=20, verbose_name="Рабочее время"),
        ),
    ]
