# Generated by Django 4.2.2 on 2023-08-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_city_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="slug",
            field=models.SlugField(blank=True, null=True, verbose_name="Слаг"),
        ),
    ]
