# Generated by Django 4.2.2 on 2023-08-04 15:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_dish_description_en_dish_description_kz_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dish",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="dish",
            name="description_kz",
        ),
        migrations.RemoveField(
            model_name="dish",
            name="description_ru",
        ),
        migrations.RemoveField(
            model_name="dish",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="dish",
            name="name_kz",
        ),
        migrations.RemoveField(
            model_name="dish",
            name="name_ru",
        ),
        migrations.RemoveField(
            model_name="food_type2",
            name="category_en",
        ),
        migrations.RemoveField(
            model_name="food_type2",
            name="category_kz",
        ),
        migrations.RemoveField(
            model_name="food_type2",
            name="category_ru",
        ),
        migrations.RemoveField(
            model_name="food_type2",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="food_type2",
            name="name_kz",
        ),
        migrations.RemoveField(
            model_name="food_type2",
            name="name_ru",
        ),
    ]
