# Generated by Django 4.2.2 on 2024-01-23 15:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_dish_percentage_for_service"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dish",
            name="percentage_for_service",
        ),
    ]
