# Generated by Django 4.2.2 on 2023-08-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_alter_city_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["z_index"],
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="dish",
            options={
                "ordering": ["z_index"],
                "verbose_name": "Блюдо",
                "verbose_name_plural": "Блюда",
            },
        ),
        migrations.AlterModelOptions(
            name="food_type2",
            options={
                "ordering": ["z_index"],
                "verbose_name": "Подкатегория",
                "verbose_name_plural": "Подкатегории",
            },
        ),
        migrations.AlterField(
            model_name="client",
            name="z_index",
            field=models.IntegerField(
                blank=True, default=1, null=True, verbose_name="Порядковый №"
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="z_index",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Порядковый №"
            ),
        ),
        migrations.AlterField(
            model_name="food_type2",
            name="z_index",
            field=models.IntegerField(default=0, verbose_name="Порядковый №"),
        ),
    ]
