# Generated by Django 4.2.2 on 2023-08-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_remove_dish_description_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="name_en",
            field=models.CharField(max_length=40, null=True, verbose_name="Город"),
        ),
        migrations.AddField(
            model_name="city",
            name="name_kz",
            field=models.CharField(max_length=40, null=True, verbose_name="Город"),
        ),
        migrations.AddField(
            model_name="city",
            name="name_ru",
            field=models.CharField(max_length=40, null=True, verbose_name="Город"),
        ),
    ]
