# Generated by Django 4.2.2 on 2023-08-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0015_food_type2_name_en_food_type2_name_kz_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="city",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="city",
            name="name_kz",
        ),
        migrations.RemoveField(
            model_name="city",
            name="name_ru",
        ),
        migrations.RemoveField(
            model_name="client",
            name="address_en",
        ),
        migrations.RemoveField(
            model_name="client",
            name="address_kz",
        ),
        migrations.RemoveField(
            model_name="client",
            name="address_ru",
        ),
        migrations.RemoveField(
            model_name="client",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="client",
            name="description_kz",
        ),
        migrations.RemoveField(
            model_name="client",
            name="description_ru",
        ),
        migrations.RemoveField(
            model_name="food_type2",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="food_type2",
            name="name_kz",
        ),
        migrations.RemoveField(
            model_name="food_type2",
            name="name_ru",
        ),
        migrations.AddField(
            model_name="dish",
            name="name_en",
            field=models.CharField(blank=True, max_length=50, verbose_name="Блюдо_EN"),
        ),
        migrations.AddField(
            model_name="dish",
            name="name_kz",
            field=models.CharField(blank=True, max_length=50, verbose_name="Блюдо_KZ"),
        ),
        migrations.DeleteModel(
            name="Client_Category",
        ),
    ]
