# Generated by Django 4.2.2 on 2023-08-05 11:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0016_remove_city_name_en_remove_city_name_kz_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dish",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="dish",
            name="name_kz",
        ),
    ]
