# Generated by Django 4.2.2 on 2024-02-07 12:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0017_dish_spicy_dish_vegetarian"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Food_type2",
            new_name="Food_type",
        ),
    ]
