# Generated by Django 4.2.2 on 2023-08-05 13:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0017_remove_dish_name_en_remove_dish_name_kz"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Client_Type",
        ),
    ]
