# Generated by Django 4.2.2 on 2023-08-05 13:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0018_delete_client_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="food_type2",
            name="category",
        ),
        migrations.DeleteModel(
            name="Food_type",
        ),
    ]
