# Generated by Django 5.0.1 on 2024-02-15 05:07

import main.models.utils.images_upload
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0018_rename_food_type2_food_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="translated",
            field=models.BooleanField(default=False, verbose_name="Перевод на 3 языка"),
        ),
        migrations.AlterField(
            model_name="client",
            name="logo",
            field=models.ImageField(
                help_text="Логотип заведения",
                upload_to=main.models.utils.images_upload.client_logo_upload_to,
                verbose_name="Лого",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="z_index",
            field=models.IntegerField(default=100, verbose_name="Порядковый №"),
        ),
    ]
