# Generated by Django 5.0.1 on 2024-02-15 05:31

import django.db.models.deletion
import main.models.utils.images_upload
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0019_client_translated_alter_client_logo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="address",
            field=models.CharField(
                help_text="Улица, дом", max_length=50, verbose_name="Адрес"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="address_en",
            field=models.CharField(
                help_text="Улица, дом", max_length=50, null=True, verbose_name="Адрес"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="address_kk",
            field=models.CharField(
                help_text="Улица, дом", max_length=50, null=True, verbose_name="Адрес"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="address_ru",
            field=models.CharField(
                help_text="Улица, дом", max_length=50, null=True, verbose_name="Адрес"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="delivery",
            field=models.BooleanField(
                help_text="Значок Доставки", verbose_name="Доставка"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="inst",
            field=models.CharField(
                blank=True,
                help_text="Ссылка на Instagram",
                max_length=100,
                verbose_name="Instagram",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="logo",
            field=models.ImageField(
                help_text="Для отображения на главной странице",
                upload_to=main.models.utils.images_upload.client_logo_upload_to,
                verbose_name="Лого",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(max_length=20, verbose_name="Наименование"),
        ),
        migrations.AlterField(
            model_name="client",
            name="outside",
            field=models.BooleanField(
                help_text="Значок Самовывоза", verbose_name="Самовывоз"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.DecimalField(
                decimal_places=0,
                help_text="Формат: '77015302812' (без +)",
                max_digits=15,
                verbose_name="Телефон",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="status",
            field=models.BooleanField(
                help_text="Отображение при поиске в Delivery", verbose_name="Активен"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="translated",
            field=models.BooleanField(
                default=False,
                help_text="Значок перевода на 3 языка",
                verbose_name="Перевод",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="two_gis",
            field=models.CharField(
                blank=True,
                help_text="Ссылка на 2Gis",
                max_length=150,
                null=True,
                unique=True,
                verbose_name="2gis",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="url_name",
            field=models.CharField(
                help_text="Путь: yaem.kz/***/menu",
                max_length=30,
                unique=True,
                verbose_name="/url",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="working_time",
            field=models.CharField(
                help_text="Формат: '00:00-24:00'",
                max_length=20,
                verbose_name="Рабочее время",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="z_index",
            field=models.IntegerField(
                default=100,
                help_text="Алматы 1-10, Астана 11-20, Караганда 21-30",
                verbose_name="Порядковый №",
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="client",
            field=models.ForeignKey(
                help_text="Блюдо какого заведения",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.client",
                verbose_name="Заведение",
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Описание блюда (120 символов)",
                max_length=120,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="Описание блюда (120 символов)",
                max_length=120,
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="description_kk",
            field=models.TextField(
                blank=True,
                help_text="Описание блюда (120 символов)",
                max_length=120,
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="description_ru",
            field=models.TextField(
                blank=True,
                help_text="Описание блюда (120 символов)",
                max_length=120,
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="food_type",
            field=models.ForeignKey(
                help_text="Подкатегория",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.food_type",
                verbose_name="Подкатегория",
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="generated",
            field=models.BooleanField(
                default=False,
                help_text="Предупреждение о генерации",
                verbose_name="Фото сгенерировано",
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="name",
            field=models.CharField(
                help_text="Наименование (40 символов)",
                max_length=40,
                verbose_name="Блюдо",
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="name_en",
            field=models.CharField(
                help_text="Наименование (40 символов)",
                max_length=40,
                null=True,
                verbose_name="Блюдо",
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="name_kk",
            field=models.CharField(
                help_text="Наименование (40 символов)",
                max_length=40,
                null=True,
                verbose_name="Блюдо",
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="name_ru",
            field=models.CharField(
                help_text="Наименование (40 символов)",
                max_length=40,
                null=True,
                verbose_name="Блюдо",
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="old_price",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                help_text="Если старая цена выше актуальной, будет отражена скидка",
                max_digits=10,
                verbose_name="Старая цена",
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="popular",
            field=models.BooleanField(
                default=False, help_text="Значок популярно", verbose_name="Популярное"
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="spicy",
            field=models.BooleanField(
                default=False, help_text="Значок остроты", verbose_name="Острое"
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="vegetarian",
            field=models.BooleanField(
                default=False,
                help_text="Значок вегетарианское",
                verbose_name="Вегетарианское",
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="z_index",
            field=models.IntegerField(
                blank=True,
                help_text="Акции: 0, Популярные: 1, Закуски: 2-10, Салаты: 11-20, Супы: 21-30, Основные: 31-40, Пиццы: 41-45, Шашлыки: 46-50, Десерты: 51-60, Безалкагольное: 61-70, Алкаголь: 71-100, Разное: 101-110",
                null=True,
                verbose_name="Порядковый №",
            ),
        ),
    ]
