# Generated by Django 4.2.2 on 2023-08-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0019_remove_food_type2_category_delete_food_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="name_en",
            field=models.CharField(max_length=40, null=True, verbose_name="Город"),
        ),
        migrations.AddField(
            model_name="city",
            name="name_kz",
            field=models.CharField(max_length=40, null=True, verbose_name="Город"),
        ),
        migrations.AddField(
            model_name="city",
            name="name_ru",
            field=models.CharField(max_length=40, null=True, verbose_name="Город"),
        ),
        migrations.AddField(
            model_name="client",
            name="description_en",
            field=models.TextField(max_length=60, null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="client",
            name="description_kz",
            field=models.TextField(max_length=60, null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="client",
            name="description_ru",
            field=models.TextField(max_length=60, null=True, verbose_name="Описание"),
        ),
    ]
