# Generated by Django 5.0.1 on 2024-02-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0020_alter_client_address_alter_client_address_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="description",
            field=models.TextField(max_length=200, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="client",
            name="description_en",
            field=models.TextField(max_length=200, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="client",
            name="description_kk",
            field=models.TextField(max_length=200, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="client",
            name="description_ru",
            field=models.TextField(max_length=200, null=True, verbose_name="Описание"),
        ),
    ]
