# Generated by Django 4.2.2 on 2024-02-17 14:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0021_alter_client_description_alter_client_description_en_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Food_type",
            new_name="Food_type2",
        ),
    ]
