# Generated by Django 4.2.2 on 2023-08-09 07:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0022_dish_description_en_dish_description_kz_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="city",
            old_name="name_kz",
            new_name="name_kk",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="address_kz",
            new_name="address_kk",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="description_kz",
            new_name="description_kk",
        ),
        migrations.RenameField(
            model_name="dish",
            old_name="description_kz",
            new_name="description_kk",
        ),
        migrations.RenameField(
            model_name="dish",
            old_name="name_kz",
            new_name="name_kk",
        ),
        migrations.RenameField(
            model_name="food_type2",
            old_name="name_kz",
            new_name="name_kk",
        ),
    ]
