# Generated by Django 4.2.2 on 2024-02-17 14:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0022_rename_food_type_food_type2"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Food_type2",
            new_name="Food_type",
        ),
    ]
