# Generated by Django 4.2.2 on 2024-01-23 15:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cart",
        ),
    ]
