# Generated by Django 4.2.2 on 2023-11-16 08:05

import banquets.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("main", "0011_alter_client_working_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeaturesOfTheBanquetHall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "features_name",
                    models.CharField(
                        max_length=256, verbose_name="Особенности банкетного зала"
                    ),
                ),
            ],
            options={
                "verbose_name": "Особенность банкетного зала",
                "verbose_name_plural": "Особенности банкетных залов",
            },
        ),
        migrations.CreateModel(
            name="KitchenType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kitchen_type",
                    models.CharField(max_length=256, verbose_name="Вид кухни"),
                ),
            ],
            options={
                "verbose_name": "Вид кухни",
                "verbose_name_plural": "Виды кухни",
            },
        ),
        migrations.CreateModel(
            name="BanquetCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Название банкетного зала",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=banquets.models.banquet_logo_upload_to,
                        verbose_name="Лого",
                    ),
                ),
                ("capacity", models.PositiveIntegerField(verbose_name="Вместимость")),
                (
                    "price_min",
                    models.PositiveIntegerField(verbose_name="Мин. цена за человека"),
                ),
                (
                    "price_max",
                    models.PositiveIntegerField(verbose_name="Макс. цена за человека"),
                ),
                ("status", models.BooleanField(verbose_name="Активен")),
                (
                    "url_name",
                    models.CharField(max_length=30, unique=True, verbose_name="/url"),
                ),
                (
                    "working_time",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Рабочее время",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Адрес",
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="WhatsApp",
                    ),
                ),
                (
                    "inst",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Instagram",
                    ),
                ),
                (
                    "two_gis",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="2gis",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        unique=True,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "z_index",
                    models.IntegerField(
                        blank=True, null=True, unique=True, verbose_name="Порядковый №"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.city",
                        verbose_name="Город",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.client",
                        verbose_name="Зал заведения:",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карточку банкетного зала",
                "verbose_name_plural": "Карточки банкетных залов",
            },
        ),
        migrations.CreateModel(
            name="Banquet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=256, verbose_name="Название зала"),
                ),
                (
                    "parking_1",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Охраняемая", "Охраняемая"),
                            ("Неохраняемая", "Неохраняемая"),
                        ],
                        max_length=256,
                        null=True,
                        verbose_name="Парковка: Охраняемая/Неохраняемая",
                    ),
                ),
                (
                    "parking_2",
                    models.CharField(
                        blank=True,
                        choices=[("Платная", "Платная"), ("Бесплатная", "Бесплатная")],
                        max_length=256,
                        null=True,
                        verbose_name="Парковка: Платная/Бесплатная",
                    ),
                ),
                (
                    "memorials",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Стоимость поминок(xxxx-xxxx)",
                    ),
                ),
                (
                    "sub_hall_capacity",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Вместимость зала",
                    ),
                ),
                (
                    "sub_hall_price_for_person",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Цена за человека(xxxx-xxxx)",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Описание пзала",
                    ),
                ),
                (
                    "hall_no",
                    models.IntegerField(blank=True, null=True, verbose_name="№ Зала"),
                ),
                (
                    "photo1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=banquets.models.subhall_photo_upload_to,
                        verbose_name="Фото 1",
                    ),
                ),
                (
                    "photo2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=banquets.models.subhall_photo_upload_to,
                        verbose_name="Фото 2",
                    ),
                ),
                (
                    "photo3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=banquets.models.subhall_photo_upload_to,
                        verbose_name="Фото 3",
                    ),
                ),
                (
                    "photo4",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=banquets.models.subhall_photo_upload_to,
                        verbose_name="Фото 4",
                    ),
                ),
                (
                    "photo5",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=banquets.models.subhall_photo_upload_to,
                        verbose_name="Фото 5",
                    ),
                ),
                (
                    "photo6",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=banquets.models.subhall_photo_upload_to,
                        verbose_name="Фото 6",
                    ),
                ),
                (
                    "banquet_card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="banquets.banquetcard",
                        verbose_name="Карточка банкетного зала",
                    ),
                ),
                (
                    "features_name",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        to="banquets.featuresofthebanquethall",
                        verbose_name="Особенности банкетного зала",
                    ),
                ),
                (
                    "kitchen_types",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        to="banquets.kitchentype",
                        verbose_name="Виды кухни",
                    ),
                ),
            ],
            options={
                "verbose_name": "Банкетный зал",
                "verbose_name_plural": "Банкетные залы",
            },
        ),
    ]
