# Generated by Django 4.2.2 on 2023-11-14 08:10

import banquets.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("main", "0011_alter_client_working_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banquet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Название банкетного зала",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=banquets.models.banquet_logo_upload_to,
                        verbose_name="Лого",
                    ),
                ),
                ("capacity", models.PositiveIntegerField(verbose_name="Вместимость")),
                (
                    "price_min",
                    models.PositiveIntegerField(verbose_name="Мин. цена за человека"),
                ),
                (
                    "price_max",
                    models.PositiveIntegerField(verbose_name="Макс. цена за человека"),
                ),
                (
                    "working_time",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Рабочее время",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Адрес",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        unique=True,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "inst",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Instagram"
                    ),
                ),
                (
                    "two_gis",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="2gis",
                    ),
                ),
                ("status", models.BooleanField(verbose_name="Активен")),
                (
                    "url_name",
                    models.CharField(max_length=30, unique=True, verbose_name="/url"),
                ),
                ("z_index", models.IntegerField(verbose_name="Порядковый №")),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.city",
                        verbose_name="Город",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.client",
                        verbose_name="Чей зал?",
                    ),
                ),
            ],
            options={
                "verbose_name": "Банкетный зал",
                "verbose_name_plural": "Банкетные залы",
            },
        ),
        migrations.CreateModel(
            name="SubHall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=256, verbose_name="Название подзала"),
                ),
                (
                    "kitchen_type",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="Виды кухни"
                    ),
                ),
                (
                    "memorials",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Стоимость поминок(xxxx-xxxx)",
                    ),
                ),
                (
                    "sub_hall_capacity",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Вместимость подзала",
                    ),
                ),
                (
                    "sub_hall_price_for_person",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Цена за человека(xxxx-xxxx)",
                    ),
                ),
                (
                    "sub_hall_peculiarities",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Особенности",
                    ),
                ),
                (
                    "parking",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Описание парковки",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Описание подзала",
                    ),
                ),
                (
                    "hall_no",
                    models.IntegerField(blank=True, null=True, verbose_name="№ Зала"),
                ),
                (
                    "photo1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=banquets.models.subhall_photo_upload_to,
                        verbose_name="Фото 1",
                    ),
                ),
                (
                    "photo2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=banquets.models.subhall_photo_upload_to,
                        verbose_name="Фото 2",
                    ),
                ),
                (
                    "photo3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=banquets.models.subhall_photo_upload_to,
                        verbose_name="Фото 3",
                    ),
                ),
                (
                    "photo4",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=banquets.models.subhall_photo_upload_to,
                        verbose_name="Фото 4",
                    ),
                ),
                (
                    "photo5",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=banquets.models.subhall_photo_upload_to,
                        verbose_name="Фото 5",
                    ),
                ),
                (
                    "photo6",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=banquets.models.subhall_photo_upload_to,
                        verbose_name="Фото 6",
                    ),
                ),
                (
                    "banquet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="banquets.banquet",
                        verbose_name="Название банкетного зала",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подзал",
                "verbose_name_plural": "Подзалы",
            },
        ),
        migrations.AddField(
            model_name="banquet",
            name="subhalls",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="banquets",
                to="banquets.subhall",
                verbose_name="Подзалы",
            ),
        ),
    ]
