# Generated by Django 4.2.2 on 2023-10-29 15:22

import banquets.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banquets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="banquet",
            name="photos",
        ),
        migrations.AddField(
            model_name="banquet",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=banquets.models.banquet_logo_upload_to,
                verbose_name="Лого",
            ),
        ),
    ]
