# Generated by Django 4.2.2 on 2023-10-30 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_alter_client_working_time"),
        ("banquets", "0002_remove_banquet_photos_banquet_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="banquet",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.client",
            ),
        ),
    ]
