# Generated by Django 4.2.2 on 2024-02-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banquets", "0002_alter_banquet_options_alter_banquetcard_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="banquetcard",
            options={
                "ordering": ("-z_index",),
                "verbose_name": "Карточка зала",
                "verbose_name_plural": "Карточки залов",
            },
        ),
        migrations.AlterField(
            model_name="banquet",
            name="memorials",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Стоимость поминок(XXXX - XXXX)",
            ),
        ),
    ]
