# Generated by Django 4.2.2 on 2023-10-31 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_alter_client_working_time"),
        ("banquets", "0003_banquet_client"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="banquet",
            name="client",
        ),
        migrations.AddField(
            model_name="banquet",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.city",
                verbose_name="Город",
            ),
        ),
        migrations.AlterField(
            model_name="banquet",
            name="price",
            field=models.PositiveIntegerField(verbose_name="Цена за человека"),
        ),
    ]
