# Generated by Django 4.2.2 on 2023-10-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banquets", "0004_remove_banquet_client_banquet_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banquet",
            name="capacity",
            field=models.PositiveIntegerField(
                choices=[(500, "500"), (1000, "1000"), (2000, "2000")],
                verbose_name="Вместимость",
            ),
        ),
        migrations.AlterField(
            model_name="banquet",
            name="price",
            field=models.PositiveIntegerField(
                choices=[(5000, "5000"), (8000, "8000"), (10000, "10000")],
                verbose_name="Цена за человека",
            ),
        ),
    ]
