# Generated by Django 4.2.2 on 2023-10-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banquets", "0005_alter_banquet_capacity_alter_banquet_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banquet",
            name="capacity",
            field=models.PositiveIntegerField(
                choices=[(500, "500"), (1000, "1000"), (2000, "2000")],
                default="Не выбрано",
                verbose_name="Вместимость",
            ),
        ),
    ]
