# Generated by Django 4.2.2 on 2023-11-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banquets", "0006_alter_banquet_capacity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="banquet",
            name="price",
        ),
        migrations.AddField(
            model_name="banquet",
            name="price_max",
            field=models.PositiveIntegerField(
                choices=[(5000, "5000"), (8000, "8000"), (10000, "10000")],
                default=1,
                verbose_name="Макс. цена за человека",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="banquet",
            name="price_min",
            field=models.PositiveIntegerField(
                choices=[(5000, "5000"), (8000, "8000"), (10000, "10000")],
                default=1000,
                verbose_name="Мин. цена за человека",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="banquet",
            name="capacity",
            field=models.PositiveIntegerField(
                choices=[(500, "500"), (1000, "1000"), (2000, "2000")],
                verbose_name="Вместимость",
            ),
        ),
    ]
