# Generated by Django 4.2.2 on 2023-11-23 05:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("banquets", "0006_banquet_parking_1_en_banquet_parking_1_kk_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="banquetcard",
            name="tarif_number",
        ),
    ]
