# Generated by Django 4.2.2 on 2023-11-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banquets", "0007_remove_banquet_price_banquet_price_max_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banquet",
            name="price_max",
            field=models.PositiveIntegerField(verbose_name="Макс. цена за человека"),
        ),
        migrations.AlterField(
            model_name="banquet",
            name="price_min",
            field=models.PositiveIntegerField(verbose_name="Мин. цена за человека"),
        ),
    ]
