# Generated by Django 4.2.2 on 2023-12-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banquets", "0007_remove_banquetcard_tarif_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banquet",
            name="description",
            field=models.CharField(
                blank=True,
                default="Добро пожаловать! Всегда рады видеть вас.",
                max_length=556,
                null=True,
                verbose_name="Описание зала",
            ),
        ),
        migrations.AlterField(
            model_name="banquet",
            name="description_en",
            field=models.CharField(
                blank=True,
                default="Добро пожаловать! Всегда рады видеть вас.",
                max_length=556,
                null=True,
                verbose_name="Описание зала",
            ),
        ),
        migrations.AlterField(
            model_name="banquet",
            name="description_kk",
            field=models.CharField(
                blank=True,
                default="Добро пожаловать! Всегда рады видеть вас.",
                max_length=556,
                null=True,
                verbose_name="Описание зала",
            ),
        ),
        migrations.AlterField(
            model_name="banquet",
            name="description_ru",
            field=models.CharField(
                blank=True,
                default="Добро пожаловать! Всегда рады видеть вас.",
                max_length=556,
                null=True,
                verbose_name="Описание зала",
            ),
        ),
        migrations.AlterField(
            model_name="banquetcard",
            name="working_time",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Рабочее время"
            ),
        ),
    ]
