# Generated by Django 4.2.2 on 2023-11-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banquets", "0008_alter_banquet_price_max_alter_banquet_price_min"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banquet",
            name="capacity",
            field=models.PositiveIntegerField(verbose_name="Вместимость"),
        ),
    ]
