# Generated by Django 4.2.2 on 2023-11-08 05:40

import banquets.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banquets", "0009_alter_banquet_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="banquet",
            name="photo1",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=banquets.models.banquet_logo_upload_to,
                verbose_name="Фото 1",
            ),
        ),
        migrations.AddField(
            model_name="banquet",
            name="photo2",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=banquets.models.banquet_logo_upload_to,
                verbose_name="Фото 2",
            ),
        ),
        migrations.AddField(
            model_name="banquet",
            name="photo3",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=banquets.models.banquet_logo_upload_to,
                verbose_name="Фото 3",
            ),
        ),
        migrations.AddField(
            model_name="banquet",
            name="photo4",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=banquets.models.banquet_logo_upload_to,
                verbose_name="Фото 4",
            ),
        ),
        migrations.AddField(
            model_name="banquet",
            name="photo5",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=banquets.models.banquet_logo_upload_to,
                verbose_name="Фото 5",
            ),
        ),
    ]
