# Generated by Django 4.2.2 on 2024-01-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banquets", "0009_alter_banquet_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banquet",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="banquet",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="banquet",
            name="description_kk",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="banquet",
            name="description_ru",
            field=models.TextField(blank=True, null=True),
        ),
    ]
