# Generated by Django 4.2.2 on 2023-11-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banquets", "0010_banquet_photo1_banquet_photo2_banquet_photo3_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banquet",
            name="description",
            field=models.TextField(
                blank=True, max_length=256, null=True, verbose_name="Описание"
            ),
        ),
    ]
