# Generated by Django 4.2.2 on 2024-01-26 10:54

import banquets.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("banquets", "0010_alter_banquet_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="banquet",
            name="photo10",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=banquets.models.subhall_photo_upload_to,
                verbose_name="Фото 10",
            ),
        ),
        migrations.AddField(
            model_name="banquet",
            name="photo7",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=banquets.models.subhall_photo_upload_to,
                verbose_name="Фото 7",
            ),
        ),
        migrations.AddField(
            model_name="banquet",
            name="photo8",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=banquets.models.subhall_photo_upload_to,
                verbose_name="Фото 8",
            ),
        ),
        migrations.AddField(
            model_name="banquet",
            name="photo9",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=banquets.models.subhall_photo_upload_to,
                verbose_name="Фото 9",
            ),
        ),
        migrations.AlterField(
            model_name="banquet",
            name="banquet_card",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="banquets.banquetcard",
                verbose_name="Карточка банкетного зала",
            ),
        ),
        migrations.AlterField(
            model_name="banquet",
            name="description",
            field=models.TextField(
                blank=True,
                default="Добро пожаловать! Всегда рады видеть вас.",
                null=True,
                verbose_name="Описание зала",
            ),
        ),
        migrations.AlterField(
            model_name="banquet",
            name="description_en",
            field=models.TextField(
                blank=True,
                default="Добро пожаловать! Всегда рады видеть вас.",
                null=True,
                verbose_name="Описание зала",
            ),
        ),
        migrations.AlterField(
            model_name="banquet",
            name="description_kk",
            field=models.TextField(
                blank=True,
                default="Добро пожаловать! Всегда рады видеть вас.",
                null=True,
                verbose_name="Описание зала",
            ),
        ),
        migrations.AlterField(
            model_name="banquet",
            name="description_ru",
            field=models.TextField(
                blank=True,
                default="Добро пожаловать! Всегда рады видеть вас.",
                null=True,
                verbose_name="Описание зала",
            ),
        ),
        migrations.AlterField(
            model_name="banquetcard",
            name="z_index",
            field=models.IntegerField(
                blank=True, default=11, null=True, verbose_name="Порядковый №"
            ),
        ),
    ]
