# Generated by Django 4.2.2 on 2023-11-08 07:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("banquets", "0011_alter_banquet_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="banquet",
            old_name="logo",
            new_name="photo",
        ),
    ]
