# Generated by Django 4.2.2 on 2023-11-08 09:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("banquets", "0012_rename_logo_banquet_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="banquet",
            old_name="photo",
            new_name="logo",
        ),
    ]
