# Generated by Django 4.2.2 on 2023-11-10 08:48

import banquets.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("banquets", "0013_rename_photo_banquet_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubHallPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=banquets.models.banquet_logo_upload_to,
                        verbose_name="Фото 1",
                    ),
                ),
                (
                    "photo2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=banquets.models.banquet_logo_upload_to,
                        verbose_name="Фото 2",
                    ),
                ),
                (
                    "photo3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=banquets.models.banquet_logo_upload_to,
                        verbose_name="Фото 3",
                    ),
                ),
                (
                    "photo4",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=banquets.models.banquet_logo_upload_to,
                        verbose_name="Фото 4",
                    ),
                ),
                (
                    "photo5",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=banquets.models.banquet_logo_upload_to,
                        verbose_name="Фото 5",
                    ),
                ),
                (
                    "photo6",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=banquets.models.banquet_logo_upload_to,
                        verbose_name="Фото 6",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubHall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, unique=True)),
                (
                    "banquet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="banquets.banquet",
                    ),
                ),
                (
                    "photos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="banquets.subhallphoto",
                    ),
                ),
            ],
        ),
    ]
