# Generated by Django 4.2.2 on 2023-11-10 08:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("banquets", "0014_subhallphoto_subhall"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="banquet",
            name="photo3",
        ),
        migrations.RemoveField(
            model_name="banquet",
            name="photo4",
        ),
        migrations.RemoveField(
            model_name="banquet",
            name="photo5",
        ),
    ]
