# Generated by Django 4.2.2 on 2023-11-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banquets", "0015_remove_banquet_photo3_remove_banquet_photo4_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="banquet",
            name="description",
        ),
        migrations.AddField(
            model_name="subhall",
            name="description",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Описание"
            ),
        ),
    ]
