# Generated by Django 4.2.2 on 2023-11-10 08:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("banquets", "0016_remove_banquet_description_subhall_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subhall",
            name="photos",
        ),
        migrations.DeleteModel(
            name="SubHallPhoto",
        ),
    ]
