# Generated by Django 4.2.2 on 2023-11-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banquets", "0017_remove_subhall_photos_delete_subhallphoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="banquet",
            name="subhalls",
            field=models.ManyToManyField(
                related_name="banquets", to="banquets.subhall", verbose_name="Подзалы"
            ),
        ),
    ]
